config/routes.rb
Rails.application.routes.draw do

  #field recording routes
  get "/fieldrecordings", to: "field_recordings#index", as: "field_recordings"
  get "/fieldrecordings/new", to: "field_recordings#new", as: "new_field_recording"

  get "/fieldrecordings/:id", to: "field_recordings#show", as: "field_recording"
  get "/fieldrecordings/:id/edit", to: "field_recordings#edit", as: "edit_field_recording"
  post "/fieldrecordings", to: "field_recordings#create"
  patch "/fieldrecordings/:id", to: "field_recordings#update"

  #artist routes
  get "/artists", to: "artists#index", as: "artists"
  get "/artists/new", to: "artists#new", as: "artist_signup"
  get "/artists/:id", to: "artists#show", as: "artist"
  get "/artists/:id/edit", to: "artists#edit", as: "edit_artist"
  post "/artists", to: "artists#create"
  patch "/artists/:id", to: "artists#update"

  #follow routes
  put "/artists/:id", to: "follows#create", as: "create_follow"
  delete "/artists/:id", to: "follows#destroy", as: "delete_follow"

  #location routes
  get "/locations", to: "locations#index", as: "locations"
  get "/locations/new", to: "locations#new", as: "new_location"
  get "/locations/:id", to: "locations#show", as: "location"
  get "/locations/:id/edit", to: "locations#edit", as: "edit_location"
  post "/locations", to: "locations#create"
  patch "/locations/:id", to: "locations#update"

  #user routes
  get "/users", to: "users#index", as: "users"
  get "/users/analysis", to: "users#analysis", as: "stats"
  get "/users/:id", to: "users#show", as: "user"
  get "/signup", to: "users#new", as: "user_signup"
  post "/users", to: "users#create"

  #session routes
  get "/login", to: "sessions#new_user", as: "login_user"
  get "/login/artist", to: "sessions#new_artist", as: "login_artist"
  post "/sessions/user", to: "sessions#log_user"
  post "/sessions/artist", to: "sessions#log_artist"
  delete "/logout", to: "sessions#destroy", as: "logout"

  #comment routes
  get "/comments/:id", to: "comments#show", as: "comment"
  get "/comments/new/:id", to: "comments#new", as: "new_comment"
  get "/comments/edit/:id", to: "comments#edit", as: "edit_comment"
  post "/comments", to: "comments#create"
  patch "/comments/:id", to: "comments#update"
  delete "/comments/:id", to: "comments#destroy", as: "delete_comment"

  #extra routes
  get "/", to: "sessions#new_user"
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :field_recordings
  has_one_attached :avatar

  is_impressionable
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  impressionist actions: [:show]

  def index
    @artists = Artist.all
    @random_artist = @artists.sample
    @recordings = @random_artist.field_recordings

  end

  def show
    @artist = Artist.find(params[:id])
    @field_recordings = @artist.field_recordings
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create!(artist_params)
    session[:artist_id] = @artist.id
    redirect_to artist_path(@artist)
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.valid?
      @artist.update(artist_params)
      redirect_to artist_path(@artist)
    else
      flash[:message] = @artist.errors.full_messages[0]
      render :edit
    end
  end

  def destroy
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :description, :avatar)
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/edit.html.erb
<div class="container">

<div class="fr-header">
Edit <%= @artist.name %>
</div>
<div class="fr-form">
<%=form_for @artist do |f|%>
<%=f.label :name%>
<%=f.text_field :name%>
<%=f.label :description%>
<%=f.text_area :description%>
<%= f.label "Photo" %><br>
<%= f.file_field :avatar %><br><br>
<%=f.submit "submit"%>
<%end%>
</div>

</div>

app/views/artists/index.html.erb
<div class="container">
<div class="fr-header">
Artists
</div>

<div class="fr-list">
<ul>
<% @artists.each do |artist| %>
<li>
<%=link_to artist.name, artist_path(artist.id) %>
</li>
<% end %>
</ul>
</div>

<div class="fr-comments">

        Featured Artist<br>
        <br>
        <% if @random_artist.avatar.attached? %>
        <img src="<%= (url_for(@random_artist.avatar)) %>"">
        <% end %>
        name: <%= link_to @random_artist.name, artist_path(@random_artist) %><br>
        recordings: <% @recordings.each do |r| %>
                    <%= link_to r.title, field_recording_path(r) %><br>   
                    <% end %>
                    
    
    
    </div>
        
        
        


</div>

app/views/artists/new.html.erb
<div class="container">

<div class="artist-header">
New Artist
</div>

<div class="artist-form">

<%= form_for @artist do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name %><br><br>
<%= f.label :description %><br>
<%= f.text_area :description %><br><br>
<%= f.label "Photo" %><br>
<%= f.file_field :avatar %><br><br>
<%= f.submit "Submit" %><br>
<% end %>

</div>

</div>

app/views/artists/show.html.erb
<div class="container">

<div class="artist-header">
<%= @artist.name %>
</div>

<div id="follow-button">

</div>


<div class="artist-content">
<% if user_logged_in? %>
<% if !followed? %>
<h3><%= link_to "+ follow", create_follow_path, method: :put %></h3>
<% else %>
<h3><%= link_to "+ edit", edit_artist_path %></h3>
<h3><%= link_to "- unfollow", delete_follow_path, method: :delete %></h3>
<% end %>
<% end %>
<h3>+ Field Recordings</h3>
<ul><% @field_recordings.each do |f|%>
<li><%= link_to f.title + " " + f.date.to_s, field_recording_path(f.id)%></li>
<% end %></ul>
<h3>+ Bio</h3>
<%= @artist.description %>
</div>



<div class="artist-picture">
          
<% if @artist.avatar.attached? %>
    <img src="<%= (url_for(@artist.avatar)) %>">
<% end %>

</div>

</div>