config/routes.rb
Rails.application.routes.draw do

  #field recording routes
  get "/fieldrecordings", to: "field_recordings#index", as: "field_recordings"
  get "/fieldrecordings/new", to: "field_recordings#new", as: "new_field_recording"

  get "/fieldrecordings/:id", to: "field_recordings#show", as: "field_recording"
  get "/fieldrecordings/:id/edit", to: "field_recordings#edit", as: "edit_field_recording"
  post "/fieldrecordings", to: "field_recordings#create"
  patch "/fieldrecordings/:id", to: "field_recordings#update"

  #artist routes
  get "/artists", to: "artists#index", as: "artists"
  get "/artists/new", to: "artists#new", as: "artist_signup"
  get "/artists/:id", to: "artists#show", as: "artist"
  get "/artists/:id/edit", to: "artists#edit", as: "edit_artist"
  post "/artists", to: "artists#create"
  patch "/artists/:id", to: "artists#update"

  #follow routes
  put "/artists/:id", to: "follows#create", as: "create_follow"
  delete "/artists/:id", to: "follows#destroy", as: "delete_follow"

  #location routes
  get "/locations", to: "locations#index", as: "locations"
  get "/locations/new", to: "locations#new", as: "new_location"
  get "/locations/:id", to: "locations#show", as: "location"
  get "/locations/:id/edit", to: "locations#edit", as: "edit_location"
  post "/locations", to: "locations#create"
  patch "/locations/:id", to: "locations#update"

  #user routes
  get "/users", to: "users#index", as: "users"
  get "/users/analysis", to: "users#analysis", as: "stats"
  get "/users/:id", to: "users#show", as: "user"
  get "/signup", to: "users#new", as: "user_signup"
  post "/users", to: "users#create"

  #session routes
  get "/login", to: "sessions#new_user", as: "login_user"
  get "/login/artist", to: "sessions#new_artist", as: "login_artist"
  post "/sessions/user", to: "sessions#log_user"
  post "/sessions/artist", to: "sessions#log_artist"
  delete "/logout", to: "sessions#destroy", as: "logout"

  #comment routes
  get "/comments/:id", to: "comments#show", as: "comment"
  get "/comments/new/:id", to: "comments#new", as: "new_comment"
  get "/comments/edit/:id", to: "comments#edit", as: "edit_comment"
  post "/comments", to: "comments#create"
  patch "/comments/:id", to: "comments#update"
  delete "/comments/:id", to: "comments#destroy", as: "delete_comment"

  #extra routes
  get "/", to: "sessions#new_user"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :follows
  has_many :field_recordings, through: :follows
  has_many :comments

  validates :username, presence: true
  validates :username, uniqueness: true

  validates :password, presence: true

  validates :email, presence: true
  validates :email, uniqueness: true

  is_impressionable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  impressionist actions: [:show]

  def index
  end

  def show
    @user = User.find(params[:id])
    @comments = @user.comments
    @follows = @user.follows
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create!(user_params)
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  end

  def destroy
  end

  def analysis
    @users = User.all
    @field_recordings = FieldRecording.all
    @artists = Artist.all
    @locations = Location.all
    @comments = Comment.all
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/analysis.html.erb
<div class="container">

<div class="fr-header">
Site stats
</div>
        
        
<div class="fr-stats">

<ul>
number of users: <%= @users.length %><br>
number of field recordings: <%= @field_recordings.length %><br>
number of artists: <%= @artists.length %><br>
number of locations: <%= @locations.length %><br>
number of comments: <%= @comments.length %><br>


<br>
<br>
Field Recording views
<br>
<br>
<% @field_recordings.each do |f| %>
<%=  link_to "#{f.title}:", field_recording_path(f.id) %><%=" #{f.impressionist_count}"%><br>
<% end %>
<br>
<br>


Artist views
<br>
<br>
<% @artists.each do |a| %>
<%=  link_to "#{a.name}:", artist_path(a.id) %><%= " #{a.impressionist_count}"%><br>
<% end %>
<br>
<br>


Location views
<br>
<br>
<% @locations.each do |l| %>
<%=  link_to "#{l.name}:", location_path(l.id)%><%= " #{l.impressionist_count}"%><br>
<% end %>
<br>


</ul>
</div>
</div>

app/views/users/edit.html.erb
<div class="container">
    
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

</div>

app/views/users/index.html.erb
<div class="container">
    
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>


</div>

app/views/users/new.html.erb
<div class="container">


<div class="user-header">
<h1>New User</h1>
</div>

<div class="user-form">

<%= form_for @user do |f| %>
<%= f.label :email %><br>
<%= f.text_field :email %><br>
<%= f.label :username %><br>
<%= f.text_field :username %><br>
<%= f.label :password %><br>
<%= f.password_field :password %><br>
<%= f.submit "Submit" %><br>
<% end %>

</div>

</div>

app/views/users/show.html.erb
<div class="container">

<div class="fr-header">
<%= @user.username %>
</div>




<div class="user-follows">
    <div class="stat-link">
    <%= link_to "Site statistics", stats_path %>
</div>
<br>
    Artists you follow
    <ul>
        <% if @follows.length == 0  %>
        <%= link_to "+ no follows yet; find an artist", artists_path %>
        <% else %>
        <% @follows.each do |f| %>
        <li> <%= link_to f.artist.name, artist_path(f.artist_id) %> </li>
        <% end %>
        <% end %>
    </ul>
</div>

<div class="user-comments">
 <div class="new-fr">
<% if user_logged_in?%> 
<%= link_to "New Field Recording", new_field_recording_path%> 
<% end %>
<br>
<br>
</div>
    Comments on Field Recordings
    <ul>
        <% if @comments.length == 0 %>
        <%= link_to "+ no comments yet; find a field recording", field_recordings_path %>
        <% else %>
        <% @comments.each do |c| %>
        <li> <%= link_to c.field_recording.title + " - " + c.comment, field_recording_path(c.field_recording) %>
            <br>

            <%= link_to "edit comment", edit_comment_path(c.id) %>
            <%= link_to "delete comment", c, method: :delete , data: {:confirm => "Delete comment?" } ,
            :title => "Delete #{c.comment}"%>
        </li>
        <% end %>
        <% end %>
    </ul>
</div>


</div>