config/routes.rb
Rails.application.routes.draw do

  #field recording routes
  get "/fieldrecordings", to: "field_recordings#index", as: "field_recordings"
  get "/fieldrecordings/new", to: "field_recordings#new", as: "new_field_recording"

  get "/fieldrecordings/:id", to: "field_recordings#show", as: "field_recording"
  get "/fieldrecordings/:id/edit", to: "field_recordings#edit", as: "edit_field_recording"
  post "/fieldrecordings", to: "field_recordings#create"
  patch "/fieldrecordings/:id", to: "field_recordings#update"

  #artist routes
  get "/artists", to: "artists#index", as: "artists"
  get "/artists/new", to: "artists#new", as: "artist_signup"
  get "/artists/:id", to: "artists#show", as: "artist"
  get "/artists/:id/edit", to: "artists#edit", as: "edit_artist"
  post "/artists", to: "artists#create"
  patch "/artists/:id", to: "artists#update"

  #follow routes
  put "/artists/:id", to: "follows#create", as: "create_follow"
  delete "/artists/:id", to: "follows#destroy", as: "delete_follow"

  #location routes
  get "/locations", to: "locations#index", as: "locations"
  get "/locations/new", to: "locations#new", as: "new_location"
  get "/locations/:id", to: "locations#show", as: "location"
  get "/locations/:id/edit", to: "locations#edit", as: "edit_location"
  post "/locations", to: "locations#create"
  patch "/locations/:id", to: "locations#update"

  #user routes
  get "/users", to: "users#index", as: "users"
  get "/users/analysis", to: "users#analysis", as: "stats"
  get "/users/:id", to: "users#show", as: "user"
  get "/signup", to: "users#new", as: "user_signup"
  post "/users", to: "users#create"

  #session routes
  get "/login", to: "sessions#new_user", as: "login_user"
  get "/login/artist", to: "sessions#new_artist", as: "login_artist"
  post "/sessions/user", to: "sessions#log_user"
  post "/sessions/artist", to: "sessions#log_artist"
  delete "/logout", to: "sessions#destroy", as: "logout"

  #comment routes
  get "/comments/:id", to: "comments#show", as: "comment"
  get "/comments/new/:id", to: "comments#new", as: "new_comment"
  get "/comments/edit/:id", to: "comments#edit", as: "edit_comment"
  post "/comments", to: "comments#create"
  patch "/comments/:id", to: "comments#update"
  delete "/comments/:id", to: "comments#destroy", as: "delete_comment"

  #extra routes
  get "/", to: "sessions#new_user"
end

app/models/field_recording.rb
class FieldRecording < ApplicationRecord
  has_one :artists
  has_one :location
  has_many :comments
  has_many :follows
  has_one_attached :avatar
  has_one_attached :recording
  validates :title, presence: true
  accepts_nested_attributes_for :location

  is_impressionable

  def self.search(search)
    where("title LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/field_recordings_controller.rb
class FieldRecordingsController < ApplicationController
  impressionist actions: [:show]

  def index
    @field_recordings = FieldRecording.all
    if params[:search]
      @field_recordings = FieldRecording.search(params[:search])
    else
      @field_recordings = FieldRecording.all
      @random_field_recording = @field_recordings.sample
      @title = @random_field_recording.title
      @artist = Artist.find { |a| a.id == @random_field_recording.artist_id }
      @location = Location.find { |l| l.id == @random_field_recording.location_id }
      @description = @random_field_recording.description
    end
  end

  def show
    @field_recording = FieldRecording.find(params[:id])
    @artist = Artist.find { |a| a.id == @field_recording.artist_id }
    @location = Location.find { |l| l.id == @field_recording.location_id }
    @comments = @field_recording.comments
    # @comments = Comment.select { |c| c.field_recording_id == @field_recording.id }
  end

  def new
    @field_recording = FieldRecording.new
    @artist = Artist.new
    @location = Location.new
  end

  def create
    @location = Location.find_or_create_by(name: params[:field_recording][:location][:name])
    @artist = Artist.find_or_create_by(name: params[:field_recording][:artist][:name])
    @field_recording = FieldRecording.create!(field_recording_params.merge(artist_id: @artist.id, location_id: @location.id))
    if @field_recording.valid?
      redirect_to @field_recording
    else
      flash[:message] = @field_recording.errors.full_messages[0]
      render :new
    end
  end

  def edit
    @artist = Artist.new
    @field_recording = FieldRecording.find(params[:id])
    @location = Location.new
  end

  def update
    @location = Location.find_or_create_by(name: params[:field_recording][:location][:name])
    @artist = Artist.find_or_create_by(name: params[:field_recording][:artist][:name])
    @field_recording = FieldRecording.find(params[:id])
    if @field_recording.valid?
      @field_recording.update(field_recording_params)
      redirect_to @field_recording
    else
      flash[:message] = @field_recording.errors.full_messages[0]
      render :edit
    end
  end

  def destroy
  end

  private

  def field_recording_params
    params.require(:field_recording).permit(:title, :date, :description, :avatar, :recording)
  end
end

app/helpers/field_recordings_helper.rb
module FieldRecordingsHelper
end

app/views/field_recordings/edit.html.erb
<div class="container">

<div class="fr-header">
Edit <%= @field_recording.title %>
</div>
<div class="fr-form">
<%= form_for @field_recording do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.fields_for @location do |location| %>
    <%= location.label :name, "Location" %>
    <%= location.text_field :name, placeholder: "Leave blank if Location is the same." %>
    <% end %>
    <%= f.fields_for @artist do |artist| %>
    <%= artist.label :name, "Artist" %>
    <%= artist.text_field :name, placeholder: "Leave blank if Artist is the same." %>
    <% end %>
<%= f.label :date %>
<%= f.date_select :date %>
<%= f.label :description %>
<%= f.text_area :description %>
<%= f.label "Photo" %>
<%= f.file_field :avatar %>
<%= f.label "Recording" %>
<%= f.file_field :recording %>
<%= f.submit "Submit" %>
<% end %>
</div>

</div>

app/views/field_recordings/index.html.erb
<div class="container">
<div class="fr-header">
    Field recordings
</div>


<div class="fr-comments">
<div class="new-fr">
<% if user_logged_in?%> 
<%= link_to "New Field Recording", new_field_recording_path%> 
<% end %>
</div>
Featured Field Recording<br>
<br>
<% if @random_field_recording.avatar.attached? %>
<img src="<%= (url_for(@random_field_recording.avatar)) %>"">
<% end %>
title: <%= link_to @title, field_recording_path(@random_field_recording) %><br>
artist: <%= link_to @artist.name, artist_path(@artist) %><br>
location: <%= link_to @location.name, location_path(@location) %><br>
date: <%= @random_field_recording.date %><br>
<div class="fr-description">
description: <%= @description %><br>
</div>
</div>








<div class="fr-list">
<% if @field_recordings.blank? %>
There are no field recordings containing the term <%= params[:search]%>.
<% end %>
<ul>
<% @field_recordings.each do |fieldrecording| %>
<li>
<%=link_to fieldrecording.title, field_recording_path(fieldrecording) %>
</li>
<% end %>
</div>

</div>

app/views/field_recordings/new.html.erb
<div class="container">

<div class="fr-header">
    New Field Recording
</div>
                
<div class="fr-form">

<%= form_for @field_recording do |f| %>
<%= f.label :title %><br>
<%= f.text_field :title %><br><br>
<%= f.fields_for @location do |location| %>
    <%= location.label :name, "Location" %><br>
    <%= location.text_field :name %><br><br>
<%end%>
<%= f.fields_for @artist do |artist| %>
    <%= artist.label :name, "Artist" %><br>
    <%= artist.text_field :name %><br><br>
<%end%>
<%= f.label :date %><br>
<%= f.date_select :date %><br><br>
<%= f.label :description %><br>
<%= f.text_area :description %><br><br>
<%= f.label "Photo" %><br>
<%= f.file_field :avatar %>
<%= f.label "Recording" %>
<%= f.file_field :recording %><br><br>
<%= f.submit "Submit" %><br>
<% end %>
</div>

</div>

app/views/field_recordings/show.html.erb
<div class="container">

<div class="fr-header">
<%= @field_recording.title %>
</div>

<div class="fr-content">
title: <%= @field_recording.title %><br>
artist: <%= link_to @artist.name, artist_path(@artist) %><br>
location: <%= link_to @location.name, location_path(@location) %><br>
date: <%= @field_recording.date %><br>
<div class="fr-description">
description: <%= @field_recording.description %><br>
</div>
</div>

<div class="fr-comments">
<% if @field_recording.avatar.attached? %>
<img src="<%= (url_for(@field_recording.avatar)) %>">
<% end %>
<% if user_logged_in? %>
<%= link_to " +edit ", edit_field_recording_path(@field_recording) %><br><br>

<% end %>
comments:
<% @comments.each do |c| %>
<li>"<%= c.comment %>" - <%= c.user.username %></li>
<% end %>
<% if user_logged_in? %>
<br>
<br>
<%= link_to "add comment", new_comment_path(@field_recording) %>
<% end %> 
<br>
<br>
<br>
<br>
</div>

</div>
<div class="fr-space"></div>
<div class="player">
    <audio controls><source src="<%= (url_for(@field_recording.recording)) %>"></audio> 
</div>